spring.application.name=agendador-tarefas
spring.data.mongodb.uri=mongodb://localhost:27017/DB_ahendador
logging.level.org.springframework.data.mongodb=DEBUG

usuario.url=localhost:8080

server.port=8081